### PR TITLE
[MOD-9384] [SVS] Fix CI builds

### PR DESCRIPTION
**Pull request by rfsaliev**
**Enable and fix SVS Index build**

A clear and concise description of what the PR is solving.

**Which issues this PR fixes**
1. This PR fixes SVS integration build issues in GitHub actions
2. This PR also fixes `svs.h` compilation error introduced by #650

**Main objects this PR modified**
1. Added `cmake/svs.cmake` - which is included in `CMakeLists.txt` and enables SVS Index support depending on OS/Platform, CPU and compiler compatibilities:
    - SVS disabled for non-x86 platforms (ARM, MacOS)
    - SVS disabled for GCC compiler version < 11.0 (e.g **debian:bullseye**)
2.  Added CMake cache variables:
    - **USE_SVS** - Enable SVSIndex. Default: `ON`, forced to `OFF` for non-compatible platforms
    - **SVS_SHARED_LIB** - Download and use SVS pre-compiled shared library for LVQ/LeanVec support. Default: `ON`, forced to `OFF` if `USE_SVS` is `OFF` or **non-GLIBC** build environment (e.g. Alpine Linux with libc MUSL).
    - **SVS_URL** - url to SVS shared library package
3. If `SVS_SHARED_LIB` is off, then SVSIndex is compiled using [ScalableVectorSearch public code](https://github.com/intel/ScalableVectorSearch) without LVQ/LeanVec support.

**Mark if applicable**

- [ ] This PR introduces API changes
- [ ] This PR introduces serialization changes

### CODE REVIEW

File: cmake/svs.cmake [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+if(POLICY CMP0135)
+    cmake_policy(SET CMP0135 NEW)
+endif()
+
+# option(SVS_EXPERIMENTAL_LEANVEC "Enable experimental LeanVec in SVS" YES)
+# if(SVS_EXPERIMENTAL_LEANVEC)
+#     add_definitions(-DSVS_EXPERIMENTAL_LEANVEC)
+# endif()
+
+# Valgrind does not support AVX512 and Valgrind in running in Debug
```
[the remark this answers is not in the document]
Comment (rfsaliev) [reply cmake/svs.cmake:12]: Without this change, I got 'illegal instruction' from valgrind 3.13 on ubuntu:focal

File: cmake/svs.cmake [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+        set(SVS_SUPPORTED 0)
+        message(STATUS "Insufficient gcc version for SVS")
+    endif()
+endif()
+
+include(CMakeDependentOption)
+
+# USE_SVS option forsibly OFF if CPU or compiler is not supported
+# elsewhere let user disable SVS
+cmake_dependent_option(USE_SVS "Build with SVS library support" ON "SVS_SUPPORTED" OFF)
```
[the remark this answers is not in the document]
Comment (rfsaliev) [reply cmake/svs.cmake:39]: SVS_SUPPORTED - is the result of SVS compatibility check
USE_SVS - is the option can be changed in CMAKE_FLAGS

File: cmake/svs.cmake [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+            svs
+            URL "${SVS_URL}"
+        )
+        FetchContent_MakeAvailable(svs)
+        list(APPEND CMAKE_PREFIX_PATH "${svs_SOURCE_DIR}")
+        find_package(svs REQUIRED)
+        set(SVS_LVQ_HEADER "svs/extensions/vamana/lvq.h")
+        set(SVS_TARGET_NAME "svs::svs_shared_library")
+    else()
+        # this file is included from python_bindings/CMakeLists.txt
```
[the remark this answers is not in the document]
Comment (rfsaliev) [reply cmake/svs.cmake:79]: yes, and `SVS sources path to be relative to this file`, this why, the variable **root** is defined and used

File: cmake/svs.cmake [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+        FetchContent_Declare(
+            svs
+            URL "${SVS_URL}"
+        )
+        FetchContent_MakeAvailable(svs)
+        list(APPEND CMAKE_PREFIX_PATH "${svs_SOURCE_DIR}")
+        find_package(svs REQUIRED)
+        set(SVS_LVQ_HEADER "svs/extensions/vamana/lvq.h")
+        set(SVS_TARGET_NAME "svs::svs_shared_library")
+    else()
```
[the remark this answers is not in the document]
Comment (rfsaliev) [reply cmake/svs.cmake:78]: when `SVS_SHARED_LIB=OFF`

File: .install/install_mkl_apt.sh [hunk 5]
```diff
@@ -0,0 +1,16 @@
...
+MODE=$1 # whether to install using sudo or not
+
+if [[ $OS_TYPE = 'Linux' ]]
+then
+    if [[ $processor = 'x86_64' ]]
+    then
+        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | $MODE tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
+        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | $MODE tee /etc/apt/sources.list.d/intel-oneapi.list
+        $MODE apt update -qq || true
+        $MODE apt install -yqq intel-oneapi-mkl-core-devel-${version}
```
[the remark this answers is not in the document]
Comment (rfsaliev) [reply .install/install_mkl_apt.sh:14]: `mkl-devel` package is required for compilation, because it contains required C++ headers

File: .install/install_mkl_apt.sh [hunk 6]
```diff
@@ -0,0 +1,16 @@
+#!/bin/bash
+version=2024.1
```
[the remark this answers is not in the document]
Comment (rfsaliev) [reply .install/install_mkl_apt.sh:2]: Sorry, do not understand the question.
This script installs MKL v2024.1 which is tested with SVS shared library

File: .install/rocky_linux_9.sh [hunk 7]
```diff
@@ -5,6 +5,10 @@ export DEBIAN_FRONTEND=noninteractive
 $MODE dnf update -y
 $MODE dnf install -y gcc-toolset-13-gcc gcc-toolset-13-gcc-c++ make wget git valgrind
 
+# Install patch tool for SVS
+$MODE dnf install -y patch
```
[the remark this answers is not in the document]
Comment (rfsaliev) [reply .install/rocky_linux_9.sh:9]: It was needed to patch SVS allocators to solve Valgrind issues.
Not needed anymore after this commit: ee12dbef56a95663f497ae08cc2590dbb1d0a2c8
Will remove.
for the rocky8 case, patch is the part of the "Development Tools" package group

File: .install/install_mkl_apt.sh (hunk 6 above)
[the remark this answers is not in the document]
Comment (meiravgri) [reply .install/install_mkl_apt.sh:2]: sorry for the typo, meant descreprancy 
intel's guide installs `intel-oneapi-mkl-devel`, while you are using `intel-oneapi-mkl-core-devel-${version}`
what is the difference (specifically using `core`)?

File: .install/install_mkl.sh [hunk 8]
```diff
@@ -0,0 +1,18 @@
+#!/bin/bash
+filename=l_BaseKit_p_2024.1.0.596.sh
```
[the remark this answers is not in the document]
Comment (meiravgri) [reply .install/install_mkl.sh:2]: ok

File: .install/install_mkl_apt.sh (hunk 6 above)
[the remark this answers is not in the document]
Comment (rfsaliev) [reply .install/install_mkl_apt.sh:2]: 'mkl-core-devel' is selected for saving disk space - this package contains the minimum set of files for SVS build.

File: cmake/svs.cmake [hunk 9]
```diff
@@ -0,0 +1,117 @@
...
+cmake_policy(SET CMP0074 NEW)
+if(POLICY CMP0135)
+    cmake_policy(SET CMP0135 NEW)
+endif()
+
+# option(SVS_EXPERIMENTAL_LEANVEC "Enable experimental LeanVec in SVS" YES)
+# if(SVS_EXPERIMENTAL_LEANVEC)
+#     add_definitions(-DSVS_EXPERIMENTAL_LEANVEC)
+# endif()
+
```
[the remark this answers is not in the document]
Comment (rfsaliev) [reply cmake/svs.cmake]: Thank you.
Artefact code.
Removed.

File: cmake/svs.cmake [hunk 10]
```diff
@@ -0,0 +1,117 @@
...
+# USE_SVS option forsibly OFF if CPU or compiler is not supported
+# elsewhere let user disable SVS
+cmake_dependent_option(USE_SVS "Build with SVS library support" ON "SVS_SUPPORTED" OFF)
+if(USE_SVS)
+    message(STATUS "SVS support enabled")
+else()
+    message(STATUS "SVS support disabled")
+endif()
+
+# try to find MKL
```
[the remark this answers is not in the document]
Comment (rfsaliev) [reply cmake/svs.cmake]: good point
thank you
fixed.

File: cmake/svs.cmake (hunk 3 above)
[the remark this answers is not in the document]
Comment (rfsaliev) [reply cmake/svs.cmake]: updated comment
please let me know if it became more clear
thank you

File: cmake/svs.cmake [hunk 11]
```diff
@@ -0,0 +1,98 @@
...
+            URL "${SVS_URL}"
+        )
+        FetchContent_MakeAvailable(svs)
+        list(APPEND CMAKE_PREFIX_PATH "${svs_SOURCE_DIR}")
+        find_package(svs REQUIRED)
+        set(SVS_LVQ_HEADER "svs/extensions/vamana/lvq.h")
+        set(SVS_TARGET_NAME "svs::svs_shared_library")
+    else()
+        # this file is included from both CMakeLists.txt and python_bindings/CMakeLists.txt
+        # so, set SVS sources path relative to this file
```
Comment (meiravgri) [inline cmake/svs.cmake:79]:
```suggestion
        # This file is included from both CMakeLists.txt and python_bindings/CMakeLists.txt
        # Set `root` relative to this file, regardless of where it is included from. 
```

File: cmake/svs.cmake (hunk 3 above)
[the remark this answers is not in the document]
Comment (meiravgri) [reply cmake/svs.cmake]: better, suggested a small clearification

File: cmake/svs.cmake [hunk 12]
```diff
@@ -0,0 +1,98 @@
...
+    set(svs_factory_file "index_factories/svs_factory.cpp")
+    set(SVS_TARGET_NAME "svs::svs")
+    if(SVS_SHARED_LIB)
+        include(FetchContent)
+        FetchContent_Declare(
+            svs
+            URL "${SVS_URL}"
+        )
+        FetchContent_MakeAvailable(svs)
+        list(APPEND CMAKE_PREFIX_PATH "${svs_SOURCE_DIR}")
```
[the remark this answers is not in the document]
Comment (rfsaliev) [reply cmake/svs.cmake:73]: In the one of `FetchContent_XXX` calls
Details in cmake documentation

File: cmake/svs.cmake (hunk 4 above)
[the remark this answers is not in the document]
Comment (rfsaliev) [reply cmake/svs.cmake:77]: This option allows to compile SVSIndex without shared library from public sources without LVQ.
But also allows to compile with LVQ using SVS private sources which contain `lvq_impl.h`.

File: cmake/svs.cmake (hunk 11 above)
Comment (rfsaliev) [reply cmake/svs.cmake]: Applied

File: cmake/svs.cmake [hunk 13]
```diff
@@ -0,0 +1,98 @@
...
+
+include(CMakeDependentOption)
+
+# USE_SVS option forcibly OFF if CPU or compiler is not supported
+# elsewhere let user disable SVS
+cmake_dependent_option(USE_SVS "Build with SVS library support" ON "SVS_SUPPORTED" OFF)
+if(USE_SVS)
+else()
+endif()
+
```
[the remark this answers is not in the document]
Comment (rfsaliev) [reply cmake/svs.cmake]: Thanks. Missed in last change.
Removed.

File: cmake/svs.cmake (hunk 10 above)
[the remark this answers is not in the document]
Comment (rfsaliev) [reply cmake/svs.cmake]: Sorry, misunderstood you:
You meant 'till end of file', but I got 'find MKL block'.
Now the whole SVS configuration is in 1 `if` block.

File: cmake/svs.cmake [hunk 14]
```diff
@@ -0,0 +1,84 @@
+cmake_minimum_required(VERSION 3.12)
+cmake_policy(SET CMP0074 NEW)
+if(POLICY CMP0135)
+    cmake_policy(SET CMP0135 NEW)
+endif()
+
+# Valgrind does not support AVX512 and Valgrind in running in Debug
+# so disable it if we are in Debug mode
+string(TOUPPER "${CMAKE_BUILD_TYPE}" uppercase_CMAKE_BUILD_TYPE)
+if(uppercase_CMAKE_BUILD_TYPE STREQUAL "DEBUG")
```
Comment (meiravgri) [inline cmake/svs.cmake:10]: please prompt here

File: cmake/svs.cmake [hunk 15]
```diff
@@ -0,0 +1,84 @@
...
+    set(SVS_SUPPORTED 0)
+    message(STATUS "SVS is not supported on this architecture")
+endif()
+
+# GCC < v11 does not support C++20 features required for SVS
+# https://gcc.gnu.org/projects/cxx-status.html
+if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
+    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "11.0")
+        set(SVS_SUPPORTED 0)
+        message(STATUS "Insufficient gcc version for SVS")
```
Comment (meiravgri) [inline cmake/svs.cmake:26]: please specify the minimal version required
```suggestion
        message(STATUS "Skipping SVS: requires GCC >= 11.")
```

File: cmake/svs.cmake (hunk 14 above)
Comment (rfsaliev) [reply cmake/svs.cmake:10]: Added status message.

File: cmake/svs.cmake (hunk 15 above)
Comment (rfsaliev) [reply cmake/svs.cmake]: Done.

**Review by meiravgri — APPROVED** [review]
